version: "3.4"

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d

  py-srv:
    build: py-srv
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - INDEX_NAME=${INDEX_NAME}
      - WAIT_HOSTS=elasticsearch:9200
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch:elasticsearch"

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #  - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
  logstash:
    build: logstash
    ports:
      - "9600:9600"
    command: sh -c "/wait && logstash -f /usr/share/logstash/pipeline/mystash.conf"
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_STATEMENT=${DB_STATEMENT}
      - INDEX_NAME=${INDEX_NAME}
      - STACK_VERSION=${STACK_VERSION}
      - WAIT_HOSTS=db:5432,elasticsearch:9200
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - 'HEAP_SIZE:1g'
      - 'LS_JAVA_OPTS=-Xms1g -Xmx1g'
    depends_on:
      - db
      - elasticsearch
    links:
      - "db:db"
      - "elasticsearch:elasticsearch"

  kibana:
    image: kibana:${STACK_VERSION}
    healthcheck:
      test: "exit 0"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch